import assets from "./assets";

const DATA = [
	{
		id: "01",
		name: "Curves",
		creator: "carrot",
		price: 9.25,
		description: "This art piece features elegant curves and abstract forms. It captures the beauty of flowing lines and shapes.Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
		image: assets.item01,
		bids: [
			{
				id: "BID-11",
				name: "Selena",
				price: 9.25,
				image: assets.person02,
				date: "June 12, 2023 at 2:20 PM",
			},
			{
				id: "BID-12",
				name: "Bella",
				price: 4.5,
				image: assets.person03,
				date: "June 13, 2023 at 11:20 PM",
			},
			{
				id: "BID-13",
				name: "Emma",
				price: 4.75,
				image: assets.person04,
				date: "June 10, 2023 at 3:30 PM",
			},
		],
	},
	{
		id: "02",
		name: "Cirles",
		creator: "Grape",
		price: 3.25,
		description: "This art piece showcases circles and geometric patterns. Grape has used vibrant colors and dynamic compositions to create a visually engaging artwork.",
		image: assets.item02,
		bids: [
			{
				id: "BID-21",
				name: "Selena",
				price: 4.05,
				image: assets.person04,
				date: "June 12, 2023 at 2:20 PM",
			},
		],
	},
	{
		id: "03",
		name: "Planet",
		creator: "apple",
		price: 95.25,
		description: "Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
		image: assets.item03,
		bids: [
			{
				id: "BID-31",
				name: "Selena",
				price: 95.25,
				image: assets.person02,
				date: "June 12, 2023 at 2:20 PM",
			},
			{
				id: "BID-32",
				name: "Bella",
				price: 95.5,
				image: assets.person03,
				date: "June 13, 2023 at 11:20 PM",
			},
		],
	},
	{
		id: "04",
		name: "Shapes",
		creator: "pine",
		price: 59.25,
		description: "This art piece depicts a planet with intricate details and textures. It represents the artist's exploration of celestial bodies and the wonders of the universe.",
		image: assets.item04,
		bids: [
			{
				id: "BID-41",
				name: "Selena",
				price: 56.25,
				image: assets.person02,
				date: "June 12, 2023 at 2:20 PM",
			},
			{
				id: "BID-42",
				name: "Bella",
				price: 59.25,
				image: assets.person03,
				date: "June 13, 2023 at 11:20 PM",
			},
			{
				id: "BID-43",
				name: "Emma",
				price: 55.15,
				image: assets.person04,
				date: "June 10, 2023 at 3:30 PM",
			},
			{
				id: "BID-44",
				name: "Olivia",
				price: 54.15,
				image: assets.person02,
				date: "June 10, 2023 at 3:30 PM",
			},
		],
	},
	{
		id: "05",
		name: "Splash",
		creator: "struberi",
		price: 10.25,
		description: "This art piece features various shapes and forms arranged in a harmonious composition",
		image: assets.item05,
		bids: [
			{
				id: "BID-51",
				name: "Selena",
				price: 10.25,
				image: assets.person02,
				date: "June 12, 2023 at 2:20 PM",
			},
		],
	},
	{
		id: "06",
		name: "Mural",
		creator: "mango",
		price: 20.25,
		description: "This art piece captures the energy and motion of splashing water.",
		image: assets.item06,
		bids: [
			{
				id: "BID-61",
				name: "Selena",
				price: 20.25,
				image: assets.person02,
				date: "June 12, 2023 at 2:20 PM",
			},
			{
				id: "BID-62",
				name: "Bella",
				price: 20.5,
				image: assets.person03,
				date: "June 13, 2023 at 11:20 PM",
			},
			{
				id: "BID-63",
				name: "Emma",
				price: 20.75,
				image: assets.person04,
				date: "June 10, 2023 at 3:30 PM",
			},
			{
				id: "BID-64",
				name: "Sza",
				price: 21.25,
				image: assets.person02,
				date: "June 10, 2023 at 3:30 PM",
			},
			{
				id: "BID-65",
				name: "Kali",
				price: 3.25,
				image: assets.person02,
				date: "June 10, 2023 at 3:30 PM",
			},
		],
	},
	{
		id: "07",
		name: "Anime Town",
		creator: "bread",
		price: 18.25,
		description: "Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Ullamcorper platea penatibus ornare egestas nulla ligula hendrerit nisl suscipit sociosqu maximus, tincidunt aptent habitant purus pharetra ultrices dapibus laoreet nisi lacinia. Porta malesuada netus vel sapien conubia porttitor aliquam ut pretium ante litora molestie senectus magna egestas sociosqu, eget aliquet fames pharetra felis posuere varius fringilla quisque in arcu montes eu ullamcorper.",
		image: assets.item07,
		bids: [],
	},
	{
		id: "08",
		name: "Phoenix",
		creator: "rice",
		price: 18.25,
		description: "Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Ullamcorper platea penatibus ornare egestas nulla ligula hendrerit nisl suscipit sociosqu maximus, tincidunt aptent habitant purus pharetra ultrices dapibus laoreet nisi lacinia. Porta malesuada netus vel sapien conubia porttitor aliquam ut pretium ante litora molestie senectus magna egestas sociosqu, eget aliquet fames pharetra felis posuere varius fringilla quisque in arcu montes eu ullamcorper.",
		image: assets.item08,
		bids: [],
	},
	{
		id: "09",
		name: "Primary Curves",
		creator: "rice",
		price: 18.25,
		description: "Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Ullamcorper platea penatibus ornare egestas nulla ligula hendrerit nisl suscipit sociosqu maximus, tincidunt aptent habitant purus pharetra ultrices dapibus laoreet nisi lacinia. Porta malesuada netus vel sapien conubia porttitor aliquam ut pretium ante litora molestie senectus magna egestas sociosqu, eget aliquet fames pharetra felis posuere varius fringilla quisque in arcu montes eu ullamcorper.",
		image: assets.item09,
		bids: [],
	},
	{
		id: "10",
		name: "Secondary Curves",
		creator: "rice",
		price: 18.25,
		description: "Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Ullamcorper platea penatibus ornare egestas nulla ligula hendrerit nisl suscipit sociosqu maximus, tincidunt aptent habitant purus pharetra ultrices dapibus laoreet nisi lacinia. Porta malesuada netus vel sapien conubia porttitor aliquam ut pretium ante litora molestie senectus magna egestas sociosqu, eget aliquet fames pharetra felis posuere varius fringilla quisque in arcu montes eu ullamcorper.",
		image: assets.item10,
		bids: [],
	},
	{
		id: "11",
		name: "Rainbow Mural",
		creator: "bread",
		price: 18.25,
		description: "Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Ullamcorper platea penatibus ornare egestas nulla ligula hendrerit nisl suscipit sociosqu maximus, tincidunt aptent habitant purus pharetra ultrices dapibus laoreet nisi lacinia. Porta malesuada netus vel sapien conubia porttitor aliquam ut pretium ante litora molestie senectus magna egestas sociosqu, eget aliquet fames pharetra felis posuere varius fringilla quisque in arcu montes eu ullamcorper.",
		image: assets.item11,
		bids: [],
	},
	{
		id: "12",
		name: "Splash",
		creator: "bread",
		price: 18.25,
		description: "Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Ullamcorper platea penatibus ornare egestas nulla ligula hendrerit nisl suscipit sociosqu maximus, tincidunt aptent habitant purus pharetra ultrices dapibus laoreet nisi lacinia. Porta malesuada netus vel sapien conubia porttitor aliquam ut pretium ante litora molestie senectus magna egestas sociosqu, eget aliquet fames pharetra felis posuere varius fringilla quisque in arcu montes eu ullamcorper.",
		image: assets.item12,
		bids: [],
	}
];

export { DATA };
